### PR TITLE
Added additional GTFS feeds, update process in README

### PR DESCRIPTION
**Pull request by pjsier**
Cleaned up instructions (putting port to port 80 so that no only IP is necessary), added PACE and Metra datasets as well

### CODE REVIEW

**Comment by thcrock** [comment]
Awesome, how did I miss this? I'll take a closer look tonight, these look like great improvements.

**Comment by pjsier** [comment]
No worries! One question I actually had about it is that the Metra GTFS goes outside of the Chicago boundaries, which makes running the general analyst extensions fail (because some routes are outside of map bounds). I think Metra would still be an important dataset though, so do you think it'd be worth including OSM data for the entire region?

Otherwise I mostly just cleaned up the router (making an actual router as opposed to using `--autoScan`), and added Jython in case people want to run the scripting extension.

**Comment by pjsier** [comment]
Addressed the comment I just made about Metra OSM data in this branch: [osmosis-edits](https://github.com/pjsier/docker-otp-chicago/tree/osmosis-edits)

It takes substantially longer though, so might not be worth ti.

**Comment by thcrock** [comment]
Yeah, including the whole Chicago metro area sounds like a lot bigger undertaking/more memory. Metra data is still worth it within the city limits, and the metro area would be good as a separate option, though I'm not sure the best place to put in 'options' in something like this.

**Comment by pjsier** [comment]
Maybe we could have the version with the Metra as a separate branch for now? It doesn't seem like we can split the Metra GTFS data to just get Chicago, but including it when it goes outside the OSM data breaks the Analyst extension. I'm not sure what the easiest way is to allow it as a separate option on build.

If that makes sense, I can pull Metra data out of my `master` branch, and maybe we can focus the Metra data in a separate branch?

**Comment by thcrock** [comment]
@pjsier I was thinking even just a different Dockerfile in the repository. Like two different directories, each with their own Dockerfile?

But that's a good point about Analyst breaking when we include data outside the OSM boundaries. Maybe we should include it by default, and put the Chicago-only Dockerfile a different directory for people who really want to save the memory and can deal with the boundary issues.

**Pull request merged**
